// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet.proto

package greet

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GreeetRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreeetRequest) Reset()         { *m = GreeetRequest{} }
func (m *GreeetRequest) String() string { return proto.CompactTextString(m) }
func (*GreeetRequest) ProtoMessage()    {}
func (*GreeetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_f133a98400313c43, []int{0}
}
func (m *GreeetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreeetRequest.Unmarshal(m, b)
}
func (m *GreeetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreeetRequest.Marshal(b, m, deterministic)
}
func (dst *GreeetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreeetRequest.Merge(dst, src)
}
func (m *GreeetRequest) XXX_Size() int {
	return xxx_messageInfo_GreeetRequest.Size(m)
}
func (m *GreeetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreeetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreeetRequest proto.InternalMessageInfo

func (m *GreeetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreeetResponse struct {
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreeetResponse) Reset()         { *m = GreeetResponse{} }
func (m *GreeetResponse) String() string { return proto.CompactTextString(m) }
func (*GreeetResponse) ProtoMessage()    {}
func (*GreeetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greet_f133a98400313c43, []int{1}
}
func (m *GreeetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreeetResponse.Unmarshal(m, b)
}
func (m *GreeetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreeetResponse.Marshal(b, m, deterministic)
}
func (dst *GreeetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreeetResponse.Merge(dst, src)
}
func (m *GreeetResponse) XXX_Size() int {
	return xxx_messageInfo_GreeetResponse.Size(m)
}
func (m *GreeetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreeetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreeetResponse proto.InternalMessageInfo

func (m *GreeetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*GreeetRequest)(nil), "greet.GreeetRequest")
	proto.RegisterType((*GreeetResponse)(nil), "greet.GreeetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	SayHello(ctx context.Context, in *GreeetRequest, opts ...grpc.CallOption) (*GreeetResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *GreeetRequest, opts ...grpc.CallOption) (*GreeetResponse, error) {
	out := new(GreeetResponse)
	err := c.cc.Invoke(ctx, "/greet.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	SayHello(context.Context, *GreeetRequest) (*GreeetResponse, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreeetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*GreeetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greet.proto",
}

func init() { proto.RegisterFile("greet.proto", fileDescriptor_greet_f133a98400313c43) }

var fileDescriptor_greet_f133a98400313c43 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x2f, 0x4a, 0x4d,
	0x2d, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x94, 0xb9, 0x78, 0xdd,
	0x8b, 0x52, 0x53, 0x53, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58,
	0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x25, 0x2e,
	0x3e, 0x98, 0xa2, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74,
	0x09, 0x26, 0xb0, 0x22, 0x10, 0xd3, 0xc8, 0x85, 0x8b, 0x1d, 0xa4, 0xa6, 0x24, 0xb5, 0x48, 0xc8,
	0x92, 0x8b, 0x23, 0x38, 0xb1, 0xd2, 0x23, 0x35, 0x27, 0x27, 0x5f, 0x48, 0x44, 0x0f, 0x62, 0x29,
	0x8a, 0x25, 0x52, 0xa2, 0x68, 0xa2, 0x10, 0x53, 0x95, 0x18, 0x9c, 0xd8, 0xa3, 0x20, 0xee, 0x4a,
	0x62, 0x03, 0xbb, 0xd2, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xfc, 0xe2, 0xef, 0xb4, 0x00,
	0x00, 0x00,
}
